services:
  backend-dev:
    build:
      context: ./backend
      target: dev
    image: genesis:dev
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - study-docker
    command: pnpm dev

  postgres-dev:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - study-docker

networks:
  study-docker:


volumes:
  postgres-data:
