services:
  postgres:
    container_name: ecommerce-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ecommerce-postgres:/var/lib/postgresql/data
    networks:
      - ecommerce

  backend:
    container_name: ecommerce-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce
    driver: bridge

volumes:
  ecommerce-postgres:
    name: ecommerce-postgres
